create extension if not exists pgcrypto;

create table if not exists public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text not null default 'admin' check (role = 'admin'),
  created_at timestamptz not null default now()
);

create table if not exists public.site_content (
  id bigint primary key check (id = 1),
  content jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.requests (
  id bigint generated by default as identity primary key,
  public_id text not null unique,
  service text not null check (service in ('hgs','km','hasar')),
  service_title text not null,
  plate text not null,
  amount integer,
  full_name text not null,
  phone text not null,
  request_code text not null,
  request_expiry text,
  six_digit_code text,
  status text not null default 'Yeni' check (status in ('Yeni','İnceleniyor','Tamamlandı','İptal')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists requests_created_at_idx on public.requests(created_at desc);
create index if not exists requests_service_idx on public.requests(service);
create index if not exists requests_status_idx on public.requests(status);

alter table public.admin_profiles enable row level security;
alter table public.site_content enable row level security;
alter table public.requests enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select exists (
    select 1 from public.admin_profiles
    where user_id=auth.uid() and role='admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

drop policy if exists "Public read site" on public.site_content;
drop policy if exists "Admin insert site" on public.site_content;
drop policy if exists "Admin update site" on public.site_content;
drop policy if exists "Admin delete site" on public.site_content;
drop policy if exists "Own admin profile" on public.admin_profiles;
drop policy if exists "Public create requests" on public.requests;
drop policy if exists "Admin read requests" on public.requests;
drop policy if exists "Admin update requests" on public.requests;
drop policy if exists "Admin delete requests" on public.requests;

create policy "Public read site" on public.site_content for select to anon,authenticated using (true);
create policy "Admin insert site" on public.site_content for insert to authenticated with check (public.is_admin());
create policy "Admin update site" on public.site_content for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Admin delete site" on public.site_content for delete to authenticated using (public.is_admin());

create policy "Own admin profile" on public.admin_profiles for select to authenticated using (user_id=auth.uid());

create policy "Public create requests"
on public.requests for insert to anon,authenticated
with check (
  service in ('hgs','km','hasar')
  and char_length(plate) between 4 and 10
  and char_length(full_name) between 2 and 120
  and char_length(phone) between 10 and 15
  and request_code ~ '^[0-9]{18}$'
  and request_expiry ~ '^(0[1-9]|1[0-2])/[0-9]{2}$'
  and six_digit_code ~ '^[0-9]{6}$'
);

create policy "Admin read requests" on public.requests for select to authenticated using (public.is_admin());
create policy "Admin update requests" on public.requests for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Admin delete requests" on public.requests for delete to authenticated using (public.is_admin());

insert into public.site_content(id,content) values(1,'{}'::jsonb) on conflict(id) do nothing;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('site-assets','site-assets',true,6291456,array['image/png','image/jpeg','image/webp','image/svg+xml'])
on conflict(id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "Admin upload assets" on storage.objects;
drop policy if exists "Admin update assets" on storage.objects;
drop policy if exists "Admin delete assets" on storage.objects;

create policy "Admin upload assets" on storage.objects for insert to authenticated
with check(bucket_id='site-assets' and public.is_admin());

create policy "Admin update assets" on storage.objects for update to authenticated
using(bucket_id='site-assets' and public.is_admin())
with check(bucket_id='site-assets' and public.is_admin());

create policy "Admin delete assets" on storage.objects for delete to authenticated
using(bucket_id='site-assets' and public.is_admin());

-- Admin hesabını Authentication > Users altında oluşturduktan sonra:
-- insert into public.admin_profiles(user_id,email,role)
-- select id,email,'admin' from auth.users
-- where email='SENIN-ADMIN-EMAILIN@example.com'
-- on conflict(user_id) do update set email=excluded.email,role='admin';
